### ISSUE TITLE
In-app link opens an in-app browser, with no possibility to return back

### ISSUE THREAD

**Issue by NamesMark** [TheBestTvarynka/Dataans#42]
**Reproduce:**
When I clicked on this link in the helper popup:
Source code: [GitHub/TbeBestTvarynka/Dataans](https://github.com/TheBestTvarynka/Dataans) 

, the github page opened inside the app. There is no "back" button or other browser controls, so the only way to return back to the dataans was to completely shut down and restart the app.

**Platform:** Windows

**Screenshot:**
![image](https://github.com/user-attachments/assets/5e4ce6bb-f6a8-498c-b196-2a853f5d199c)

**Comment by TheBestTvarynka** [comment]
Yeah, I know about it. Actually, it happens only on Windows :)
I just forgot to create an issue. Thank you for reporting!
