### ISSUE TITLE
Config and theme files not opening (Windows)

### ISSUE THREAD

**Issue by NamesMark** [TheBestTvarynka/Dataans#43]
**Reproduce:**
Clicks on these don't do anything for me:
1. Edit config file
2. Edit config file (open config file location icon)
3. theme_dark.toml file
4. theme_dark.toml file (open theme file location icon)

**Platform:** Windows

**Expected:**
Would open the relevant files\folders in `install_location\dataans\resources\configs\...`

**Comment by TheBestTvarynka** [comment]
> Clicks on these don't do anything for me:

1. **Edit config file**. It should open the config file in your default editor.
2. **Edit config file (open config file location icon)**. It should open the config file location in File Explorer.
3. **theme_dark.toml file**. It should open the theme config file in your default editor.
4. **theme_dark.toml file (open theme file location icon)**. It should open the theme config file location in File Explorer.

And all of them work for me on Linux and Windows. Can you attack the log file?

**Comment by NamesMark** [comment]
Hmm I can't even see those handlers being called at all after I've added debug logs to them, I'll investigate on my own, looks like some shenanigans

**Comment by TheBestTvarynka** [comment]
> Hmm I can't even see those handlers being called at all after I've added debug logs to them

you should see something like this:

![image](https://github.com/user-attachments/assets/592bb3aa-38b4-4838-9db4-d60f45ae1351)

do not forget to set the `DATAANS_LOG` env var:

|name|value|
|-|-|
|DATAANS_LOG|`dataans=trace`|

**Comment by NamesMark** [comment]
Clarification: with `dataans=error` and `dataans=warn` it doesn't work, with `info` and beyond it works 🤔

**Comment by NamesMark** [comment]
Ah, I get it. It's because it's called like this `info!(open_config_file_result = ?opener::open(&config_file_path));` so when the log is filtered out, `::open()` never gets called. Simple fix.
