### ISSUE TITLE
Feature request: Note export

### ISSUE THREAD

**Issue by NamesMark** [TheBestTvarynka/Dataans#46]
As notes are stored in the DB, the user might want to extract them and move elsewhere, like into Obsidian. Having this flexibility might help with adoption - the user doesn't feel "locked in" dataans, and feels that their notes are safe. 

So it might be useful to export(/import?) the notes as .md files (with spaces as directories?).

**Comment by TheBestTvarynka** [comment]
I agree with you. The user should not be "_locked in_". We should investigate other note-taking apps, write down what import formats they support, and implement the most common one (or a few ones)

**Comment by TheBestTvarynka** [comment]
> We should investigate other note-taking apps

Would you like to do that?

**Comment by NamesMark** [comment]
Exporting as markdown seems to be the most useful option.

Below: import/export by different app

| App              | .md | .txt | HTML  | PDF   | CSV   | JSON  | Other                        |
|------------------|----------------|-------------------|-------|-------|-------|-------|-----------------------------|
| Obsidian         | ✅/✅           | ✅/✅              | ❌/✅* | ❌/❌  | ❌/❌  | ❌/❌  |                             |
| Notion           | ✅/✅           | ❌/✅              | ✅/✅  | ❌/❌  | ✅/✅  | ❌/❌  | ENEX*, CSV            |
| Evernote         | ❌/❌           | ✅/❌              | ✅/✅  | ❌/❌  | ❌/❌  | ❌/❌  | ENEX (Evernote Export)      |
| Telegram         | ❌/❌           | ❌/❌              | ❌/✅  | ❌/❌  | ❌/❌  | ❌/❌  |                             |
| OneNote          | ❌/❌           | ❌/❌              | ❌/❌  | ✅/✅  | ❌/❌  | ❌/❌  | OneNote Format (.one)       |
| Google Keep      | ❌/❌           | ❌/❌              | ✅*/❌ | ❌/❌  | ❌/✅  | ✅*/✅ | Google Takeout              |
| Apple Notes      | ❌/❌           | ❌/❌              | ❌/❌  | ✅*/❌ | ❌/❌  | ❌/❌  |                             |
| Simplenote       | ✅/✅           | ✅/✅              | ❌/❌  | ❌/❌  | ❌/❌  | ❌/❌  |                             |
| Standard Notes   | ✅/✅           | ✅/✅              | ❌/❌  | ❌/❌  | ❌/❌  | ❌/❌  |                             |
| Notable          | ✅/✅           | ✅/✅              | ❌/❌  | ❌/❌  | ❌/❌  | ❌/❌  |                             |
| Zettlr           | ✅/✅           | ✅/✅              | ❌/✅  | ✅/✅  | ❌/❌  | ❌/❌  | Org Mode (.org)             |
| logseq           | ✅/✅           | ❌/✅*             | ❌/❌  | ❌/❌  | ❌/❌  | ✅*/✅ | Org Mode (.org)             |
| Typora           | ✅/✅           | ✅/✅              | ✅/✅  | ✅/✅  | ❌/❌  | ❌/❌  |                             |
| The Archive      | ✅/✅           | ✅/✅              | ❌/❌  | ❌/❌  | ❌/❌  | ❌/❌  |                             |

The only question is whether to export as
1. Space as a directory, notes as files, or
2. Space as a file, notes sequential
(maybe even support both, might depend on how people are using dataans)


Tangential note: if we were to also consider importing into dataans, then
- .md again first priority, covers most of the common apps
- plain text (txt), imho, can be treated 100% the same as .md if an app only exports txt
- HTML (from telegram or Evernote) might require some research or a custom script to convert from HTML to md + make sure pictures or other files are preserved
- JSON might need a specific script for each app support, which should be rather easy to implement, but as it's custom and not general - low priority

**Comment by TheBestTvarynka** [comment]
Wow, massive work!

> Exporting as markdown seems to be the most useful option.

Yes, I agree with you. 👍 

> The only question is whether to export as

Let's make it configurable. Sometimes users may want to export one space as one page. But in other situations, the user may want to import only some notes to another app.
So, as you said, I think we should support both.

> if we were to also consider importing into dataans

It would be a great improvement. I don't plan to implement it in the near future, but if you consider implementing it, then let's discuss it in a separate issue. We'll agree on the main design points and you will be ready to start.

> * .md again first priority, covers most of the common apps
> * plain text (txt), imho, can be treated 100% the same as .md if an app only exports txt
> * HTML (from telegram or Evernote) might require some research (I'll need to test [this](https://github.com/suntong/html2md)) or a custom script to convert from HTML to md + make sure pictures or other files are preserved
> * JSON might need a specific script for each app support, which should be rather easy to implement, but as it's custom and not general - low priority

👍

**Comment by TheBestTvarynka** [comment]
@NamesMark I've implemented data exporting in #62. Now you can export the app data in two formats:

- `Md`. Three options are implemented:
  - All data in one file.
  - File per space.
  - File per note.
- `Json`. I created a custom schema. The main purpose of this option is to import the data into the app and ability to make backups. I need it because I plan to eliminate the `polodb` crate and replace it with the `sqlite` client.
