### ISSUE TITLE
All notes has been removed after the app restart

### ISSUE THREAD

**Issue by TheBestTvarynka** [TheBestTvarynka/Dataans#50]
Sometimes after the app restart, I can get an emty app:

![image](https://github.com/user-attachments/assets/f8ab67a9-0d9f-4142-a897-6cbd170b1b03)

It looks like all the data has been deleted or something. If I look at the `db` folder, then I will find that the FB file is empty:

![image](https://github.com/user-attachments/assets/7dc74bff-ccec-41ba-b0ea-301d1c98342e)

I don't know why and what the reason is.

**Comment by TheBestTvarynka** [comment]
hmmm, looks like this one may be related to this issue: https://github.com/PoloDB/PoloDB/discussions/137 
but I still don't know why it happens very rarely... 🤔

**Comment by TheBestTvarynka** [comment]
Now I cannot create any new spaces or notes... It weird...
Only if I delete db files manually, I'll be able to create new spaces successfully...
Now I cannot reproduce it again...

hm. The polodb version has not been changed. `Cargo.lock` file hasn't been touched since October 16:

![image](https://github.com/user-attachments/assets/d77ab7d3-334a-490e-9af8-3966c2f429fc)

**Comment by TheBestTvarynka** [comment]
I assumed that maybe it was caused by force quit or process kill. I tried to kill the app with Task Manager, tried to restart/shut down my laptop, and so on. I didn't manage to reproduce this issue. It is weird... 🤔

**Comment by TheBestTvarynka** [comment]
During the migration to Tauri 2, I added the following line of code:
https://github.com/TheBestTvarynka/Dataans/pull/52/files#diff-e2609b8ec57c998ad48a8e195cd213daf83bfc838ed2ef2687dc79e8aad70952R120

I hope it will fix this issue. I'll close this issue if I do not face it in the next few months.

**Comment by NamesMark** [comment]
Looks scary, to be honest. Maybe it's worth considering pivoting to something else, or at least keeping some sort of a backup copy of the DB?

**Comment by TheBestTvarynka** [comment]
> Looks scary, to be honest. Maybe it's worth considering pivoting to something else, or at least keeping some sort of a backup copy of the DB?

I agree with you. I have big plans for the next major version. I plan to migrate storage to something else and add backup support.
